# format with black
repos:
- repo: https://github.com/psf/black
  rev: 21.12b0
  hooks:
  -   id: black
      stages: [push]
# lint with ruff
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.0.156
  hooks:
    - id: ruff
      stages: [push]
      
# prevent secrets from being commited
- repo: https://github.com/sirwart/ripsecrets.git
  rev: v0.1.3
  hooks:
  -   id: ripsecrets
      stages: [commit]

# enforce conventional commit messages  
- repo: https://github.com/commitizen-tools/commitizen
  rev: master
  hooks:
    - id: commitizen
    - id: commitizen-branch
      stages: [push]