# enforce uniform formating
repos:
- repo: local
  hooks:
  -   id: lint
      name: Run format and style checkers
      entry: make
      args: ['lint_check']
      language: system
      stages: [push]

# enforce conventional commit messages  
- repo: local
  hooks:
    - id: test
      name: Runu unit tests
      entry: make 
      args: ['test']
      language: system
      stages: [push]