"""sync db with model

Revision ID: da9a304a67ce
Revises: bb1cf18c089c
Create Date: 2022-11-25 22:54:55.879439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da9a304a67ce'
down_revision = 'bb1cf18c089c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
